/*Copyright (c) 2017-2018 offline.com All Rights Reserved.
 This software is the confidential and proprietary information of offline.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with offline.com*/
package com.mobile.test_alltypes;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Table1 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`TABLE1`")
public class Table1 implements Serializable {

    private Integer id;
    private String column2;
    private String column3;
    private Date column4;
    private Timestamp column5;
    private Boolean column6;
    private Time column7;
    private String column8;
    private Time column9;
    private Timestamp column10;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`COLUMN2`", nullable = true, length = 255)
    public String getColumn2() {
        return this.column2;
    }

    public void setColumn2(String column2) {
        this.column2 = column2;
    }

    @Column(name = "`COLUMN3`", nullable = true, length = 255)
    public String getColumn3() {
        return this.column3;
    }

    public void setColumn3(String column3) {
        this.column3 = column3;
    }

    @Column(name = "`COLUMN4`", nullable = true)
    public Date getColumn4() {
        return this.column4;
    }

    public void setColumn4(Date column4) {
        this.column4 = column4;
    }

    @Column(name = "`COLUMN5`", nullable = true)
    public Timestamp getColumn5() {
        return this.column5;
    }

    public void setColumn5(Timestamp column5) {
        this.column5 = column5;
    }

    @Column(name = "`COLUMN6`", nullable = true)
    public Boolean getColumn6() {
        return this.column6;
    }

    public void setColumn6(Boolean column6) {
        this.column6 = column6;
    }

    @Column(name = "`COLUMN7`", nullable = true)
    public Time getColumn7() {
        return this.column7;
    }

    public void setColumn7(Time column7) {
        this.column7 = column7;
    }

    @Column(name = "`COLUMN8`", nullable = true, length = 255)
    public String getColumn8() {
        return this.column8;
    }

    public void setColumn8(String column8) {
        this.column8 = column8;
    }

    @Column(name = "`COLUMN9`", nullable = true)
    public Time getColumn9() {
        return this.column9;
    }

    public void setColumn9(Time column9) {
        this.column9 = column9;
    }

    @Column(name = "`COLUMN10`", nullable = true)
    public Timestamp getColumn10() {
        return this.column10;
    }

    public void setColumn10(Timestamp column10) {
        this.column10 = column10;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Table1)) return false;
        final Table1 table1 = (Table1) o;
        return Objects.equals(getId(), table1.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

